// <auto-generated />
namespace HotelEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tablesedit33 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablesedit33));
        
        string IMigrationMetadata.Id
        {
            get { return "201808121507045_tablesedit33"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
